### ISSUE TITLE
Build error: "Undefined reference to '_Detect'"

### ISSUE THREAD

**Issue by JPhilipp** [DaVikingCode/UnityDetectHeadset#11]
Great tool, thank you. Building used to work, but to switch to 64 bit architecture for Google Play Store requirements, [following this advice](https://forum.unity.com/threads/googleplay-64bit-console-warning.672988/#post-4509415) I had to switch the Player -> Other Settings -> Scripting Backend from "Mono" to "IL2CPP", then ticking all available Target Architecture options (using Unity 2019.2 final). When I do, building throws a very long error, including the following:

> Failed running E:\_misc\programs\Unity\2019.2.0f1\Editor\Data\il2cpp/build/il2cpp.exe
> ...
> C:\projects\Chatty\Temp\StagingArea\Il2Cpp\il2cppOutput/Assembly-CSharp-firstpass.cpp:388: **error: undefined reference to '_Detect'**
> clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

Removing the headset detection code once again lets me build error-free. Is there a proper workaround for this issue? Thanks!

**Comment by alamboley** [comment]
Hey, this is related to #4. I didn't have time to look at it yet.

**Comment by JPhilipp** [comment]
Thanks.
