### ISSUE TITLE
Could you add the Bluetooth Headset detect?

### ISSUE THREAD

**Issue by human890209** [DaVikingCode/UnityDetectHeadset#2]
Hi,
I'm using Android and it works. But it only detects line-in headset, Bluetooth headset is ignored.
I'm not a programmer, so I hope you could add the Bluetooth detection.

It surprised me that YOU made "A Blind Legend"!  What a coincidence : ) I like it very much. Good work indeed!

**Comment by antoniohof** [comment]
Just created a pull request with bluetooth headset detection on IOS. -> #3 
Added the code for Android too, but it's untested and you'll need to build the .jar to test it.

**Comment by human890209** [comment]
Sorry, I only know some C# to use Unity. Build jar is beyond my skill. TT

**Comment by CheeseBrownie** [comment]
Also not familiar with building jar files. Are you able to push an updated version of the .jar for us?

**Comment by 13Flo** [comment]
@alamboley Same here. Any chance you could recompile the JAR with a more recent version of Android please?

**Comment by alamboley** [comment]
Done via #7!
